---
- name: Get Gitlab repository installation script
  get_url:
      url: "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh"
      dest: /tmp/gitlab-runner.script.deb.sh
      mode: 0744

- name: Install Gitlab repository
  shell: bash /tmp/gitlab-runner.script.deb.sh

- name: Install GitLab Runner
  apt: name=gitlab-runner state=latest
