---
- name: Install Docker
  import_tasks: docker.yml

- name: Install GitLab Runner 
  import_tasks: install.yml

- name: Set global options
  import_tasks: setup.yml

- name: Register GitLab Runner
  import_tasks: register-runner.yml
  when: gitlab_runner_registration_token != ''
